Fix `propertyDiscardLimit`.
parsonsmatt/hspec-hedgehog pull request #45
Opened 2024-08-23 16:42 UTC by ChickenProp

QuickCheck has a [max discard ratio][1], i.e. a max value for `numDiscardedTests/maxSuccessTests`. Hedgehog just has an absolute discard count. So to bring them in line, we multiply max discard ratio by max successful tests.

Nitpick: if quickcheck runs more than `maxSuccessTests` successful tests for some reason (maybe coverage?) then it uses the current number of successful tests. Hedehog is also capable of running more than the naive maximum. In that case, it won't increase the discard limit.

The default quickcheck args are 100 successes and a discard ratio of 10. So if quickcheck has seen 200 successes, it'll allow up to 2000 discards. But if hedgehog has seen 200 successes, it'll still only allow up to 1000 disards.

[1]: https://github.com/nick8325/quickcheck/blob/f43aead829566f10aa3ef7c630351ed5918b3cc0/src/Test/QuickCheck/Test.hs#L325C1-L325C128

2024-08-23 22:40 UTC, ChickenProp commented
Oh right, I forgot that test suites are a thing. Will fix next week.

2024-08-27 23:34 UTC, sol requested changes
This looks good, except for the code comment.

Please also add a change log entry (major version bump).

2024-08-27 23:34 UTC, sol commented on src/Test/Hspec/Hedgehog.hs
> +                        DiscardLimit $ maxDiscardRatio qcArgs * maxTests
Code comments are a code smell, as they tend to go out of sync with the actual implementation.

For that reason:

1. If you think it's important, you can introduce a local variable that describes in code what your comment is trying to convey, e.g. `absoluteDiscardLimit = maxDiscardRatio qcArgs * maxTests`.
1. Alternatively, you may just delete the comment.

2024-08-27 23:35 UTC, sol commented
@ChickenProp please also squash/force push.

2024-08-28 07:15 UTC, ChickenProp commented
Sure thing, done.

2024-08-28 11:48 UTC, sol approved these changes

2024-08-28 11:48 UTC, merged